apiVersion: v2
name: healthcare-platform
description: AI-Driven Healthcare Booking & HRTech Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - healthcare
  - booking
  - ai
  - hrtech
home: https://github.com/healthcare-platform/healthcare-platform
sources:
  - https://github.com/healthcare-platform/healthcare-platform
maintainers:
  - name: Healthcare Platform Team
    email: team@healthcare-platform.com